import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    Server, Database, Cpu, Cloud, Layers, Plus, Edit2, UserX, UserCheck, Eye, X
} from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';
import './AnalystDashboard.css';
import './AdminPanel.css';

const INITIAL_USERS = [
    { id: 1, name: 'Ahmed Hassan', role: 'Analyst', email: 'ahmed.hassan@asgus1.gov.pk', status: 'Active', lastLogin: '28 Feb 2026 14:22', zones: [] },
    { id: 2, name: 'Sara Malik', role: 'Analyst', email: 'sara.malik@asgus1.gov.pk', status: 'Active', lastLogin: '28 Feb 2026 13:45', zones: [] },
    { id: 3, name: 'Capt. Imran Shah', role: 'Field Officer', email: 'imran.shah@asgus1.gov.pk', status: 'Active', lastLogin: '28 Feb 2026 12:30', zones: ['Quetta', 'Zhob', 'Pishin'] },
    { id: 4, name: 'Omar Farooq', role: 'Analyst', email: 'omar.farooq@asgus1.gov.pk', status: 'Active', lastLogin: '27 Feb 2026 09:15', zones: [] },
    { id: 5, name: 'Lt. Asad Khan', role: 'Field Officer', email: 'asad.khan@asgus1.gov.pk', status: 'Active', lastLogin: '27 Feb 2026 08:00', zones: ['Swat', 'Dir'] },
    { id: 6, name: 'Maj. Tariq Aziz', role: 'Field Officer', email: 'tariq.aziz@asgus1.gov.pk', status: 'Inactive', lastLogin: '25 Feb 2026 16:30', zones: ['Kech'] },
    { id: 7, name: 'Zara Ahmed', role: 'Analyst', email: 'zara.ahmed@asgus1.gov.pk', status: 'Active', lastLogin: '28 Feb 2026 11:00', zones: [] },
    { id: 8, name: 'System Admin', role: 'Admin', email: 'admin@asgus1.gov.pk', status: 'Active', lastLogin: '28 Feb 2026 21:40', zones: [] },
];

const ACTIVITY_LOG = [
    { id: 1, time: '21:40', col: '#3B82F6', desc: 'System Admin logged in' },
    { id: 2, time: '21:17', col: '#22C55E', desc: 'Alert ALT-0047 marked as Monitoring by Ahmed Hassan' },
    { id: 3, time: '20:28', col: '#F59E0B', desc: 'Zone Explorer accessed by Sara Malik' },
    { id: 4, time: '20:01', col: '#3B82F6', desc: 'Report RPT-008 generated by Omar Farooq' },
    { id: 5, time: '19:45', col: '#22C55E', desc: 'Observation OBS-2841 reviewed by Ahmed Hassan' },
    { id: 6, time: '19:30', col: '#EF4444', desc: 'Critical alert ALT-0046 triggered in Kech District' },
    { id: 7, time: '18:55', col: '#F59E0B', desc: 'Field Officer Capt. Imran Shah submitted observation OBS-2840' },
    { id: 8, time: '18:22', col: '#3B82F6', desc: 'User Zara Ahmed added by System Admin' },
    { id: 9, time: '17:45', col: '#EF4444', desc: 'Critical alert ALT-0041 triggered in Swat Valley' },
    { id: 10, time: '17:10', col: '#22C55E', desc: 'Report RPT-007 downloaded by Ahmed Hassan' },
    { id: 11, time: '16:30', col: '#3B82F6', desc: 'User Maj. Tariq Aziz deactivated by System Admin' },
    { id: 12, time: '15:58', col: '#F59E0B', desc: 'Analytics page accessed by Sara Malik' },
    { id: 13, time: '14:22', col: '#EF4444', desc: 'Critical alert ALT-0047 triggered in Swat Valley' },
    { id: 14, time: '14:15', col: '#22C55E', desc: 'Zone Detail Quetta viewed by Ahmed Hassan' },
    { id: 15, time: '13:45', col: '#3B82F6', desc: 'System backup completed successfully' }
];

const generateLog = () => {
    const events = [];
    const descs = [
        { col: '#3B82F6', txt: 'System Admin logged in' },
        { col: '#22C55E', txt: 'Alert marked as Monitoring by Ahmed Hassan' },
        { col: '#F59E0B', txt: 'Zone Explorer accessed by Sara Malik' },
        { col: '#3B82F6', txt: 'Report generated by Omar Farooq' },
        { col: '#22C55E', txt: 'Observation reviewed by Ahmed Hassan' },
        { col: '#EF4444', txt: 'Critical alert triggered in Kech District' },
        { col: '#F59E0B', txt: 'Field Officer submitted observation' },
        { col: '#3B82F6', txt: 'User Zara Ahmed added by System Admin' },
        { col: '#EF4444', txt: 'Critical alert triggered in Swat Valley' },
        { col: '#22C55E', txt: 'Report downloaded by Ahmed Hassan' },
        { col: '#3B82F6', txt: 'System backup completed successfully' }
    ];

    let now = new Date();
    for (let i = 0; i < 30; i++) {
        let d = new Date(now.getTime() - Math.floor(Math.random() * 7 * 24 * 60 * 60 * 1000));
        let ev = descs[Math.floor(Math.random() * descs.length)];
        events.push({
            id: i + 100,
            dateObj: d,
            dateStr: d.toISOString().split('T')[0],
            time: `${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}`,
            col: ev.col,
            desc: ev.txt
        });
    }
    return events.sort((a, b) => b.dateObj - a.dateObj);
};

const FULL_LOG = generateLog();

const RolePill = ({ role }) => {
    const col = role === 'Analyst' ? '#F59E0B' : role === 'Field Officer' ? '#22C55E' : '#3B82F6';
    return (
        <span style={{ background: `${col}1A`, color: col, border: `1px solid ${col}4D`, borderRadius: 4, padding: '2px 8px', fontSize: 11, fontWeight: 700, letterSpacing: '0.03em' }}>
            {role.toUpperCase()}
        </span>
    );
};

const StatusPill = ({ status }) => {
    const col = status === 'Active' ? '#22C55E' : '#666';
    return (
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: status === 'Active' ? '#FFF' : '#888', fontSize: 12, fontWeight: 600 }}>
            <div style={{ width: 6, height: 6, borderRadius: '50%', background: col }}></div>
            {status}
        </span>
    );
};

export default function AdminPanel() {
    const navigate = useNavigate();
    const [sidebarCollapsed, setSidebarCollapsed] = useState(true);
    const [time, setTime] = useState(new Date().toLocaleTimeString('en-US', { hour12: false }));
    const [users, setUsers] = useState(INITIAL_USERS);

    const [modalMode, setModalMode] = useState(null); // 'add' or 'edit'
    const [editingUser, setEditingUser] = useState(null);
    const [deactivateUser, setDeactivateUser] = useState(null);
    const [showFullLog, setShowFullLog] = useState(false);
    const [filterFrom, setFilterFrom] = useState('');
    const [filterTo, setFilterTo] = useState('');

    const [formName, setFormName] = useState('');
    const [formEmail, setFormEmail] = useState('');
    const [formRole, setFormRole] = useState('Analyst');
    const [formZones, setFormZones] = useState([]);
    const [formPass, setFormPass] = useState('');
    const [submitting, setSubmitting] = useState(false);

    const [toast, setToast] = useState(null);

    useEffect(() => {
        const t = setInterval(() => setTime(new Date().toLocaleTimeString('en-US', { hour12: false })), 1000);
        return () => clearInterval(t);
    }, []);

    const showToast = (msg) => {
        setToast(msg);
        setTimeout(() => setToast(null), 3000);
    };

    const openAddModal = () => {
        setFormName(''); setFormEmail(''); setFormRole('Analyst'); setFormZones([]); setFormPass('');
        setModalMode('add');
    };

    const openEditModal = (u) => {
        setEditingUser(u.id);
        setFormName(u.name); setFormEmail(u.email); setFormRole(u.role); setFormZones(u.zones || []); setFormPass('');
        setModalMode('edit');
    };

    const handleZoneToggle = (zoneName) => {
        setFormZones(prev => prev.includes(zoneName) ? prev.filter(z => z !== zoneName) : [...prev, zoneName]);
    };

    const genPassword = () => setFormPass(Math.random().toString(36).slice(-10) + 'X!');

    const saveUser = () => {
        setSubmitting(true);
        setTimeout(() => {
            if (modalMode === 'add') {
                const newUser = { id: Date.now(), name: formName, role: formRole, email: formEmail, status: 'Active', lastLogin: 'Never', zones: formRole === 'Field Officer' ? formZones : [] };
                setUsers([newUser, ...users]);
                showToast('User created successfully');
            } else {
                setUsers(users.map(u => u.id === editingUser ? { ...u, name: formName, role: formRole, email: formEmail, zones: formRole === 'Field Officer' ? formZones : [] } : u));
                showToast('User updated successfully');
            }
            setSubmitting(false);
            setModalMode(null);
        }, 2000);
    };

    const toggleStatus = (id, newStatus) => {
        setUsers(users.map(u => u.id === id ? { ...u, status: newStatus } : u));
        showToast(`User ${newStatus.toLowerCase()}d`);
        setDeactivateUser(null);
    };

    const filteredLog = FULL_LOG.filter(entry => {
        if (filterFrom && entry.dateStr < filterFrom) return false;
        if (filterTo && entry.dateStr > filterTo) return false;
        return true;
    });

    const healthWidgets = [
        { title: 'API Server', icon: Server, code: 'online', color: '#22C55E', up: '99.8%' },
        { title: 'PostgreSQL Database', icon: Database, code: 'online', color: '#22C55E', up: '99.5%' },
        { title: 'AI Microservice', icon: Cpu, code: 'online', color: '#22C55E', up: '98.2%' },
        { title: 'Azure App Service', icon: Cloud, code: 'degraded', color: '#F59E0B', up: 'High latency detected' },
        { title: 'PostGIS Extension', icon: Layers, code: 'online', color: '#22C55E', up: '99.9%' }
    ];

    return (
        <div className="dashboard-container">
            <Topbar subtitle="Admin Panel" />
            <div className="main-wrapper">
                <Sidebar collapsed={sidebarCollapsed} setCollapsed={setSidebarCollapsed} />

                <div className="admin-page">
                    <div className="admin-header">
                        <div>
                            <h1>Admin Panel</h1>
                            <p>System management and user administration</p>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                            <span className="mono" style={{ color: '#888', fontSize: 13 }}>{new Date().toISOString().substring(0, 10)} &middot; {time} PKT</span>
                            <div className="admin-live-pill">
                                <div className="live-dot" style={{ background: '#22C55E' }}></div> SYSTEM ONLINE
                            </div>
                        </div>
                    </div>

                    {/* Section 1: Health Strip */}
                    <div className="admin-card health-strip">
                        {healthWidgets.map((w, i) => (
                            <div className="health-item" key={i} title="Last checked: 21:43:05 PKT">
                                <div className="health-icon-wrapper" style={{ background: `${w.color}1A`, color: w.color }}>
                                    <w.icon size={18} />
                                </div>
                                <div>
                                    <div className="health-title">{w.title}</div>
                                    <div className="health-status" style={{ color: w.color }}>
                                        <div className="live-dot" style={{ background: w.color, width: 6, height: 6 }}></div>
                                        {w.code.toUpperCase()}
                                    </div>
                                    <div className="health-uptime">{w.up} {w.code === 'online' ? 'uptime' : ''}</div>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Section 2: Stats Row */}
                    <div className="admin-stats-row">
                        <div className="admin-card admin-stat-card">
                            <div className="admin-stat-val" style={{ color: '#3B82F6' }}>12</div>
                            <div className="admin-stat-lbl">Total Users</div>
                        </div>
                        <div className="admin-card admin-stat-card">
                            <div className="admin-stat-val" style={{ color: '#22C55E' }}>4</div>
                            <div className="admin-stat-lbl">Active Sessions</div>
                        </div>
                        <div className="admin-card admin-stat-card">
                            <div className="admin-stat-val" style={{ color: '#F59E0B' }}>8</div>
                            <div className="admin-stat-lbl">Reports Generated Today</div>
                        </div>
                        <div className="admin-card admin-stat-card">
                            <div className="admin-stat-val" style={{ color: '#F97316' }}>2</div>
                            <div className="admin-stat-lbl">System Alerts</div>
                        </div>
                    </div>

                    {/* Section 3: Two Col */}
                    <div className="admin-two-col">
                        <div className="admin-card" style={{ padding: 0 }}>
                            <div style={{ padding: '16px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #1E1E1E' }}>
                                <h3 style={{ margin: 0, fontSize: 16, color: '#FFF' }}>User Management</h3>
                                <button className="btn-blue" onClick={openAddModal}><Plus size={16} /> Add User</button>
                            </div>
                            <table className="admin-table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Role</th>
                                        <th>Email</th>
                                        <th>Status</th>
                                        <th>Last Login</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {users.map(u => (
                                        <tr key={u.id} className="admin-row">
                                            <td style={{ fontWeight: 700, color: '#F5F5F5' }}>{u.name}</td>
                                            <td><RolePill role={u.role} /></td>
                                            <td style={{ color: '#999' }}>{u.email}</td>
                                            <td><StatusPill status={u.status} /></td>
                                            <td style={{ color: '#666', fontFamily: 'Space Mono', fontSize: 12 }}>{u.lastLogin}</td>
                                            <td>
                                                <div style={{ display: 'flex', gap: 8 }}>
                                                    <button className="icon-btn" onClick={() => openEditModal(u)} title="Edit"><Edit2 size={14} /></button>
                                                    {u.status === 'Active' ? (
                                                        <button className="icon-btn danger" onClick={() => setDeactivateUser(u)} title="Deactivate"><UserX size={14} /></button>
                                                    ) : (
                                                        <button className="icon-btn success" onClick={() => toggleStatus(u.id, 'Active')} title="Activate"><UserCheck size={14} /></button>
                                                    )}
                                                </div>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        <div className="admin-card activity-log-card" style={{ height: '100%', padding: 20 }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                <h3 style={{ margin: 0, fontSize: 16, color: '#FFF' }}>Activity Log</h3>
                                <span style={{ color: '#666', fontSize: 12 }}>Today</span>
                            </div>
                            <div className="activity-list">
                                {ACTIVITY_LOG.map(a => (
                                    <div key={a.id} className="activity-item">
                                        <div className="activity-dot" style={{ background: a.col }}></div>
                                        <div className="activity-time">{a.time}</div>
                                        <div>{a.desc}</div>
                                    </div>
                                ))}
                                <div style={{ textAlign: 'center', marginTop: 16 }}>
                                    <button onClick={() => setShowFullLog(true)} style={{ background: 'transparent', border: 'none', color: '#3B82F6', fontWeight: 600, fontSize: 13, cursor: 'pointer' }}>View Full Log</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Modals */}
                {modalMode && (
                    <div className="modal-overlay" onClick={() => !submitting && setModalMode(null)}>
                        <div className="modal-card" onClick={e => e.stopPropagation()} style={{ width: 440 }}>
                            <div className="modal-header">
                                <h3>{modalMode === 'add' ? 'Add New User' : 'Edit User'}</h3>
                                <button className="close-btn" onClick={() => setModalMode(null)} disabled={submitting}><X size={18} /></button>
                            </div>
                            <div className="topbar-divider" style={{ width: '100%', margin: '16px 0' }}></div>

                            <div className="admin-input-group">
                                <label>Full Name</label>
                                <input type="text" className="admin-input" value={formName} onChange={e => setFormName(e.target.value)} placeholder="e.g. John Doe" />
                            </div>
                            <div className="admin-input-group">
                                <label>Email Address</label>
                                <input type="email" className="admin-input" value={formEmail} onChange={e => setFormEmail(e.target.value)} placeholder="name@asgus1.gov.pk" />
                            </div>
                            <div className="admin-input-group">
                                <label>Role</label>
                                <select className="admin-input" value={formRole} onChange={e => setFormRole(e.target.value)}>
                                    <option value="Analyst">Analyst</option>
                                    <option value="Field Officer">Field Officer</option>
                                    <option value="Admin">Admin</option>
                                </select>
                            </div>
                            {formRole === 'Field Officer' && (
                                <div className="admin-input-group">
                                    <label>Assigned Zones</label>
                                    <div className="admin-zones-grid">
                                        {['Quetta', 'Kech', 'Zhob', 'Pishin', 'Swat', 'Dir'].map(z => (
                                            <label key={z} className="admin-checkbox-lbl">
                                                <input type="checkbox" checked={formZones.includes(z)} onChange={() => handleZoneToggle(z)} />
                                                {z}
                                            </label>
                                        ))}
                                    </div>
                                </div>
                            )}
                            <div className="admin-input-group">
                                <label>Temporary Password</label>
                                <div style={{ display: 'flex', gap: 8 }}>
                                    <input type="text" className="admin-input" value={formPass} onChange={e => setFormPass(e.target.value)} style={{ flex: 1, fontFamily: 'Space Mono' }} />
                                    <button className="icon-btn" style={{ width: 40, height: 40 }} onClick={genPassword} title="Generate Password"><Eye size={18} /></button>
                                </div>
                            </div>

                            <div style={{ marginTop: 24, display: 'flex', justifyContent: 'flex-end', gap: 12 }}>
                                <button className="btn-ghost" onClick={() => setModalMode(null)} disabled={submitting}>Cancel</button>
                                <button className="btn-blue" onClick={saveUser} disabled={submitting || !formName || !formEmail}>
                                    {submitting ? <div className="spinner black" style={{ width: 14, height: 14, borderWidth: 2, borderColor: '#fff white white white' }}></div> : modalMode === 'add' ? 'Create User' : 'Save Changes'}
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {deactivateUser && (
                    <div className="modal-overlay" onClick={() => setDeactivateUser(null)}>
                        <div className="modal-card" onClick={e => e.stopPropagation()} style={{ width: 360, textAlign: 'center' }}>
                            <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 16 }}>
                                <div style={{ width: 48, height: 48, borderRadius: '50%', background: 'rgba(239, 68, 68, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#EF4444' }}>
                                    <UserX size={24} />
                                </div>
                            </div>
                            <h3 style={{ margin: '0 0 8px', fontSize: 18 }}>Deactivate {deactivateUser.name}?</h3>
                            <p style={{ margin: '0 0 24px', fontSize: 13, color: '#888' }}>This will prevent the user from logging in. You can reactivate them later at any time.</p>
                            <div style={{ display: 'flex', gap: 12, justifyContent: 'center' }}>
                                <button className="btn-ghost" onClick={() => setDeactivateUser(null)}>Cancel</button>
                                <button className="btn-danger" onClick={() => toggleStatus(deactivateUser.id, 'Inactive')}>Deactivate User</button>
                            </div>
                        </div>
                    </div>
                )}

                {showFullLog && (
                    <div className="modal-overlay" onClick={() => setShowFullLog(false)}>
                        <div className="modal-card" onClick={e => e.stopPropagation()} style={{ width: 800 }}>
                            <div className="modal-header">
                                <h3>Full Activity Log</h3>
                                <button className="close-btn" onClick={() => setShowFullLog(false)}><X size={18} /></button>
                            </div>
                            <div className="topbar-divider" style={{ width: '100%', margin: '16px 0' }}></div>

                            <div style={{ display: 'flex', gap: 16, marginBottom: 20 }}>
                                <div className="admin-input-group" style={{ marginBottom: 0, flex: 1 }}>
                                    <label>From Date</label>
                                    <input type="date" className="admin-input" value={filterFrom} onChange={e => setFilterFrom(e.target.value)} />
                                </div>
                                <div className="admin-input-group" style={{ marginBottom: 0, flex: 1 }}>
                                    <label>To Date</label>
                                    <input type="date" className="admin-input" value={filterTo} onChange={e => setFilterTo(e.target.value)} />
                                </div>
                                <div style={{ display: 'flex', alignItems: 'flex-end' }}>
                                    <button className="btn-blue" style={{ height: 38 }} onClick={() => { }}>Filter</button>
                                </div>
                            </div>

                            <div className="activity-list" style={{ maxHeight: 500, overflowY: 'auto', paddingRight: 10 }}>
                                {filteredLog.map(a => (
                                    <div key={a.id} className="activity-item">
                                        <div className="activity-dot" style={{ background: a.col }}></div>
                                        <div className="activity-time" style={{ width: 120 }}>{a.dateStr} {a.time}</div>
                                        <div>{a.desc}</div>
                                    </div>
                                ))}
                                {filteredLog.length === 0 && (
                                    <div style={{ padding: 20, textAlign: 'center', color: '#666' }}>No activity found in selected date range.</div>
                                )}
                            </div>
                        </div>
                    </div>
                )}

            </div>
            {toast && <div className="success-toast" style={{ zIndex: 9999, borderColor: '#3B82F6', color: '#3B82F6', background: 'rgba(59, 130, 246, 0.1)' }}>{toast}</div>}
        </div>
    );
}
