import React, { useState, useEffect, useRef, useContext } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import L from 'leaflet';
import {
    Home, PlusCircle, Clock, Settings, LogOut, ChevronLeft, ChevronRight,
    MapPin, Camera, X, Check, Upload, AlertTriangle, ChevronDown, FileText
} from 'lucide-react';
import { UserContext } from '../App';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';
import './AnalystDashboard.css';
import './FieldOfficerDashboard.css';

// ─── Constants & Dummy Data ───────────────────────────────────────────────────
const ASSIGNED_ZONES = [
    { name: 'Quetta', province: 'Balochistan', lat: 30.18, lng: 67.0, risk: 'Critical', color: '#EF4444', lastActivity: '14:22 UTC' },
    { name: 'Zhob', province: 'Balochistan', lat: 31.34, lng: 69.45, risk: 'High', color: '#F97316', lastActivity: '12:15 UTC' },
    { name: 'Pishin', province: 'Balochistan', lat: 30.58, lng: 66.98, risk: 'Medium', color: '#F59E0B', lastActivity: '11:45 UTC' }
];

const INITIAL_HISTORY = [
    { id: 'OBS-2841', zone: 'Pishin', type: 'Locust Activity', status: 'Reviewed', severity: 'Medium', scale: 'Large scale', desc: 'Observed dense locust cluster moving NE across agricultural fields. Approximately 8 sq km affected.', reviewer: 'Ahmed Hassan', time: '10:30 PKT', riskColor: '#F59E0B' },
    { id: 'OBS-2840', zone: 'Quetta', type: 'Animal Herd', status: 'Reviewed', severity: 'Low', scale: 'Medium', desc: 'Large cattle herd migrating south of Quetta bypass road. No locust activity observed.', reviewer: 'Sara Malik', time: '09:15 PKT', riskColor: '#22C55E' },
    { id: 'OBS-2839', zone: 'Zhob', type: 'Unusual Movement', status: 'Submitted', severity: 'High', scale: 'Large', desc: 'Unidentified movement pattern detected in sector 7. Awaiting analyst confirmation.', time: '08:45 PKT', riskColor: '#F97316' },
    { id: 'OBS-2838', zone: 'Pishin', type: 'No Activity', status: 'Reviewed', severity: 'Low', scale: 'Small', desc: 'Routine patrol of sector 3. No anomalous activity detected. Terrain clear.', reviewer: 'Ahmed Hassan', time: 'Yesterday', riskColor: '#22C55E' },
    { id: 'OBS-2837', zone: 'Quetta', type: 'Locust Activity', status: 'Flagged', severity: 'Critical', scale: 'Massive', desc: 'Extremely dense swarm formation observed near water reservoir. Immediate response recommended.', time: 'Yesterday', riskColor: '#EF4444', flagged: true }
];

const STATUS_COLORS = {
    Submitted: '#F59E0B',
    Reviewed: '#22C55E',
    Flagged: '#EF4444'
};

// ─── Shared Components ────────────────────────────────────────────────────────
const RiskPill = ({ risk, color }) => (
    <span style={{ background: `${color}1A`, color: color, border: `1px solid ${color}4D`, borderRadius: 4, padding: '2px 8px', fontSize: 11, fontWeight: 700, letterSpacing: '0.03em' }}>
        {risk.toUpperCase()}
    </span>
);

// FOSidebar and FOTopbar removed, using global Sidebar and Topbar

// ─── Modals ───────────────────────────────────────────────────────────────────
const FOReportModal = ({ onClose, onShowToast }) => {
    const [reportType, setReportType] = useState('Observation Summary');
    const [includeCharts, setIncludeCharts] = useState(true);
    const [fromDate, setFromDate] = useState('2026-02-21');
    const [toDate, setToDate] = useState('2026-02-28');
    const [generating, setGenerating] = useState(false);
    const [selectedZone, setSelectedZone] = useState(ASSIGNED_ZONES[0].name);

    const handleGenerate = () => {
        setGenerating(true);
        setTimeout(() => {
            const content = `ASGUS-1 GSR FIELD OFFICER REPORT\n======================\nZone: ${selectedZone}\nReport Type: ${reportType}\nDate Range: ${fromDate} to ${toDate}\nGenerated: ${new Date().toISOString()}\n\nThis report was generated by the ASGUS-1 GSR Field Officer Portal.`;
            const blob = new Blob([content], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `asgus1-fo-report-${Date.now()}.txt`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            setGenerating(false);
            onClose();
            onShowToast('Report downloaded successfully');
        }, 2000);
    };

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal-card" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h3>Generate Field Report</h3>
                    <button className="close-btn" onClick={onClose}><X size={18} /></button>
                </div>
                <div className="topbar-divider" style={{ width: '100%', margin: '16px 0' }}></div>
                <div className="modal-body">
                    <div className="input-group">
                        <label>Zone</label>
                        <select className="modal-input" value={selectedZone} onChange={e => setSelectedZone(e.target.value)} style={{ cursor: 'pointer' }}>
                            {ASSIGNED_ZONES.map(z => <option key={z.name} value={z.name}>{z.name}</option>)}
                        </select>
                    </div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <div className="input-group"><label>From</label><input type="date" value={fromDate} onChange={e => setFromDate(e.target.value)} className="modal-input" /></div>
                        <div className="input-group"><label>To</label><input type="date" value={toDate} onChange={e => setToDate(e.target.value)} className="modal-input" /></div>
                    </div>
                    <div className="input-group">
                        <label>Report Type</label>
                        <div className="pill-group">
                            {['Observation Summary', 'Zone Activity Log', 'Field Report'].map(t => (
                                <button
                                    key={t}
                                    className={`pill-btn ${reportType === t ? 'active' : ''}`}
                                    style={reportType === t ? { background: '#22C55E', color: '#000', borderColor: '#22C55E' } : {}}
                                    onClick={() => setReportType(t)}
                                >
                                    {t}
                                </button>
                            ))}
                        </div>
                    </div>
                    <div className="toggle-group">
                        <span>Include Charts</span>
                        <label className="switch">
                            <input type="checkbox" checked={includeCharts} onChange={() => setIncludeCharts(!includeCharts)} />
                            <span className="slider round" style={includeCharts ? { background: '#22C55E' } : {}}></span>
                        </label>
                    </div>
                    <button className="generate-btn" disabled={generating} onClick={handleGenerate} style={{ background: '#22C55E', color: '#000' }}>
                        {generating ? <div className="spinner black"></div> : 'GENERATE PDF →'}
                    </button>
                </div>
            </div>
        </div>
    );
};

// ─── Main Page Component ──────────────────────────────────────────────────────
const FieldOfficerDashboard = () => {
    const navigate = useNavigate();
    const location = useLocation();
    const [sidebarCollapsed, setSidebarCollapsed] = useState(true);

    // Map ref
    const mapRef = useRef(null);
    const mapInstanceRef = useRef(null);

    // Selected Zone state
    const [selectedZone, setSelectedZone] = useState('Quetta');

    useEffect(() => {
        if (location.hash) {
            const hash = location.hash.replace('#', '');
            const id = hash + '-section';
            const element = document.getElementById(id) || document.getElementById(hash);
            if (element) {
                setTimeout(() => element.scrollIntoView({ behavior: 'smooth' }), 50);
            }
        }
    }, [location.hash]);

    // Form state
    const [formZone, setFormZone] = useState('');
    const [formType, setFormType] = useState('Locust Activity');
    const [formDesc, setFormDesc] = useState('');
    const [formLat, setFormLat] = useState('');
    const [formLng, setFormLng] = useState('');
    const [formSeverity, setFormSeverity] = useState('');
    const [formScale, setFormScale] = useState('Small (< 1 sq km)');
    const [formNotes, setFormNotes] = useState('');
    const [formFile, setFormFile] = useState(null);

    // Form UI
    const [errors, setErrors] = useState({});
    const [submitting, setSubmitting] = useState(false);
    const [toast, setToast] = useState(null);
    const [showReportModal, setShowReportModal] = useState(false);

    // History
    const [history, setHistory] = useState(INITIAL_HISTORY);
    const [expandedCard, setExpandedCard] = useState(null);

    useEffect(() => {
        if (mapInstanceRef.current) return;
        if (!mapRef.current) return;

        const map = L.map(mapRef.current, {
            center: [30.5, 67.5],
            zoom: 8,
            zoomControl: true,
            attributionControl: false,
            backgroundColor: '#080808'
        });

        L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
            attribution: '© CARTO'
        }).addTo(map);

        ASSIGNED_ZONES.forEach(zone => {
            const icon = L.divIcon({
                className: 'custom-div-icon',
                html: `<div class="marker-pulse-wrapper">
                         <div class="marker-ring" style="border-color:${zone.color}"></div>
                         <div class="marker-core" style="background-color:${zone.color}; box-shadow: 0 0 10px ${zone.color}"></div>
                       </div>`,
                iconSize: [24, 24],
                iconAnchor: [12, 12]
            });

            L.marker([zone.lat, zone.lng], { icon })
                .bindPopup(`
                    <div style="background:#111; padding:8px; border-radius:4px; border:1px solid #222; color:#fff; font-family:'Space Grotesk',sans-serif;">
                        <div style="font-weight:700; margin-bottom:4px; font-size:14px;">${zone.name}</div>
                        <div style="font-size:10px; color:${zone.color}; border:1px solid ${zone.color}44; border-radius:3px; padding:1px 4px; display:inline-block; margin-bottom:6px;">${zone.risk.toUpperCase()}</div>
                        <div style="font-family:'Space Mono',monospace; font-size:10px; color:#888;">Last detected: ${zone.lastActivity}</div>
                    </div>
                `, { className: 'custom-dark-popup' })
                .addTo(map);
        });

        map.getContainer().addEventListener('mouseleave', () => map.dragging.disable());
        map.getContainer().addEventListener('mouseenter', () => map.dragging.enable());

        mapInstanceRef.current = map;

        return () => {
            if (mapInstanceRef.current) {
                mapInstanceRef.current.remove();
                mapInstanceRef.current = null;
            }
        };
    }, []);

    const handleAutoFillGPS = () => {
        if (!formZone) {
            setErrors({ ...errors, zone: true });
            return;
        }
        const z = ASSIGNED_ZONES.find(x => x.name === formZone);
        if (z) {
            // Add slight random offset to simulate GPS inaccuracy
            setFormLat((z.lat + (Math.random() * 0.02 - 0.01)).toFixed(5));
            setFormLng((z.lng + (Math.random() * 0.02 - 0.01)).toFixed(5));
            setErrors({ ...errors, zone: false });
        }
    };

    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setFormFile(e.target.files[0]);
        }
    };

    const submitObservation = () => {
        const newErrors = {};
        if (!formZone) newErrors.zone = true;
        if (!formDesc) newErrors.desc = true;

        if (Object.keys(newErrors).length > 0) {
            setErrors(newErrors);
            return;
        }

        setSubmitting(true);
        setErrors({});

        setTimeout(() => {
            const newId = `OBS-${Math.floor(1000 + Math.random() * 9000)}`;

            const newEntry = {
                id: newId,
                zone: formZone,
                type: formType,
                status: 'Submitted',
                severity: formSeverity || 'Low',
                scale: formScale,
                desc: formDesc,
                time: new Date().toLocaleTimeString('en-US', { hour12: false }).substring(0, 5) + ' PKT',
                riskColor: formSeverity === 'CRITICAL' ? '#EF4444' : formSeverity === 'HIGH' ? '#F97316' : formSeverity === 'MEDIUM' ? '#F59E0B' : '#22C55E'
            };

            setHistory([newEntry, ...history]);

            setToast(`Observation submitted successfully · ID: ${newId}`);
            setTimeout(() => setToast(null), 4000);

            // Reset form
            setFormZone('');
            setFormDesc('');
            setFormLat('');
            setFormLng('');
            setFormSeverity('');
            setFormNotes('');
            setFormFile(null);
            setSubmitting(false);
        }, 2000);
    };

    return (
        <div className="dashboard-container">
            <Topbar subtitle="Field Officer Portal" />
            <div className="main-wrapper">
                <Sidebar collapsed={sidebarCollapsed} setCollapsed={setSidebarCollapsed} />

                <main style={{ flex: 1, overflowY: 'auto', background: '#080808' }}>
                    <div className="fo-content-area">

                        {/* Section 1 — Assignment Card */}
                        <div className="fo-card" style={{ marginBottom: 16, position: 'relative' }}>
                            <button
                                onClick={() => setShowReportModal(true)}
                                style={{ position: 'absolute', top: 24, right: 24, padding: '8px 16px', background: '#22C55E', color: '#000', border: 'none', borderRadius: 6, fontWeight: 700, fontSize: 13, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, transition: 'background 0.2s' }}
                                onMouseOver={e => e.currentTarget.style.background = '#16A34A'}
                                onMouseOut={e => e.currentTarget.style.background = '#22C55E'}
                            >
                                <FileText size={16} /> Generate Report
                            </button>
                            <div className="fo-assignment-layout" style={{ marginTop: 12 }}>
                                <div className="fo-assignment-left">
                                    <div className="fo-muted-caps">Today's Assignment</div>
                                    <div className="fo-officer-name">Capt. Imran Shah</div>
                                    <div className="fo-officer-sub">Senior Field Officer &middot; Badge #FO-2847</div>
                                    <div className="fo-shift">
                                        <Clock size={14} /> <span>Shift: 08:00 &mdash; 20:00 PKT</span>
                                    </div>
                                    <div className="fo-duty-pill-inline">
                                        <div className="live-dot" style={{ background: '#22C55E' }}></div> ON DUTY
                                    </div>
                                </div>
                                <div className="fo-assignment-right">
                                    <div className="fo-stat-box">
                                        <div className="fo-stat-val" style={{ color: '#22C55E' }}>3</div>
                                        <div className="fo-stat-lbl">Assigned Zones</div>
                                    </div>
                                    <div className="fo-stat-divider"></div>
                                    <div className="fo-stat-box">
                                        <div className="fo-stat-val" style={{ color: '#FFF' }}>2</div>
                                        <div className="fo-stat-lbl">Observations Today</div>
                                    </div>
                                    <div className="fo-stat-divider"></div>
                                    <div className="fo-stat-box">
                                        <div className="fo-stat-val" style={{ color: '#F97316' }}>1</div>
                                        <div className="fo-stat-lbl">Pending Reviews</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Section 2 — Two Column Layout */}
                        <div className="fo-two-col-layout" style={{ marginBottom: 16 }}>
                            {/* Left: Map */}
                            <div className="fo-card fo-map-card">
                                <div className="fo-card-header">
                                    <h3 style={{ margin: 0, fontSize: 16, color: '#FFF' }}>Assigned Zones</h3>
                                    <div style={{ fontSize: 13, color: '#666' }}>3 zones under monitoring</div>
                                </div>
                                <div style={{ height: 320, width: '100%', position: 'relative', isolation: 'isolate', zIndex: 0 }} ref={mapRef}></div>
                            </div>

                            {/* Right: Zone List */}
                            <div className="fo-card fo-zones-card">
                                <h3 style={{ margin: '0 0 16px', fontSize: 16, color: '#FFF' }}>My Zones</h3>
                                <div className="fo-zone-list">
                                    {ASSIGNED_ZONES.map(z => (
                                        <div
                                            key={z.name}
                                            className={`fo-zone-row ${selectedZone === z.name ? 'active' : ''}`}
                                            onClick={() => setSelectedZone(z.name)}
                                        >
                                            <div className="fo-zone-row-top">
                                                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                                    <div style={{ width: 8, height: 8, borderRadius: '50%', background: z.color }}></div>
                                                    <div>
                                                        <div style={{ fontWeight: 700, color: '#FFF', fontSize: 14 }}>{z.name}</div>
                                                        <div style={{ fontSize: 11, color: '#666' }}>{z.province}</div>
                                                    </div>
                                                </div>
                                                <RiskPill risk={z.risk} color={z.color} />
                                            </div>
                                            <div style={{ paddingLeft: 18, marginTop: 4, fontFamily: 'Space Mono', fontSize: 10, color: '#666' }}>
                                                Last activity: {z.lastActivity}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                                <button
                                    className={`fo-view-btn ${!selectedZone ? 'disabled' : ''}`}
                                    onClick={() => selectedZone && navigate(`/zone/${selectedZone}`)}
                                    disabled={!selectedZone}
                                >
                                    View Zone Details &rarr;
                                </button>
                            </div>
                        </div>

                        {/* Section 3 — Submit Observation */}
                        <div className="fo-card" id="submit-section" style={{ marginBottom: 16 }}>
                            <div className="fo-card-header" style={{ padding: '0 0 16px', borderBottom: '1px solid #1A1A1A' }}>
                                <div>
                                    <h3 style={{ margin: 0, fontSize: 20, color: '#FFF' }}>Submit Field Observation</h3>
                                    <div style={{ fontSize: 13, color: '#666', marginTop: 4 }}>Report ground-level findings to supplement AI detection data</div>
                                </div>
                                <div className="fo-live-form-pill">
                                    <div className="live-dot" style={{ background: '#22C55E' }}></div> LIVE FORM
                                </div>
                            </div>

                            <div className="fo-form-grid">
                                {/* Row 1 */}
                                <div className="fo-form-group">
                                    <label className="fo-muted-caps">Zone <span style={{ color: '#EF4444' }}>*</span></label>
                                    <select
                                        className={`fo-input ${errors.zone ? 'error' : ''}`}
                                        value={formZone} onChange={e => { setFormZone(e.target.value); setErrors({ ...errors, zone: false }) }}
                                    >
                                        <option value="" disabled>Select assigned zone...</option>
                                        <option value="Quetta">Quetta</option>
                                        <option value="Zhob">Zhob</option>
                                        <option value="Pishin">Pishin</option>
                                    </select>
                                    {errors.zone && <div className="fo-error-text">This field is required</div>}
                                </div>
                                <div className="fo-form-group">
                                    <label className="fo-muted-caps">Type</label>
                                    <select className="fo-input" value={formType} onChange={e => setFormType(e.target.value)}>
                                        <option value="Locust Activity">Locust Activity</option>
                                        <option value="Animal Herd">Animal Herd</option>
                                        <option value="Unusual Movement">Unusual Movement</option>
                                        <option value="No Activity">No Activity</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </div>

                                {/* Row 2 */}
                                <div className="fo-form-group full-width">
                                    <label className="fo-muted-caps">Observation Details <span style={{ color: '#EF4444' }}>*</span></label>
                                    <textarea
                                        className={`fo-input ${errors.desc ? 'error' : ''}`}
                                        placeholder="Describe what you observed &mdash; movement direction, approximate scale, affected area, any notable characteristics..."
                                        style={{ height: 120, resize: 'vertical' }}
                                        value={formDesc} onChange={e => { setFormDesc(e.target.value); setErrors({ ...errors, desc: false }) }}
                                    />
                                    {errors.desc && <div className="fo-error-text">This field is required</div>}
                                </div>

                                {/* Row 3 */}
                                <div className="fo-form-group">
                                    <label className="fo-muted-caps" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                        <span>GPS Coordinates</span>
                                        <button className="fo-autofill-btn" onClick={handleAutoFillGPS}><MapPin size={12} /> Auto-fill</button>
                                    </label>
                                    <div style={{ display: 'flex', gap: 12 }}>
                                        <input type="text" className="fo-input" placeholder="Lat" value={formLat} onChange={e => setFormLat(e.target.value)} style={{ flex: 1, fontFamily: 'Space Mono' }} />
                                        <input type="text" className="fo-input" placeholder="Long" value={formLng} onChange={e => setFormLng(e.target.value)} style={{ flex: 1, fontFamily: 'Space Mono' }} />
                                    </div>
                                </div>
                                <div className="fo-form-group">
                                    <label className="fo-muted-caps">Severity</label>
                                    <div className="fo-severity-pill-group">
                                        {[
                                            { lbl: 'LOW', val: 'LOW', col: '#22C55E' },
                                            { lbl: 'MEDIUM', val: 'MEDIUM', col: '#F59E0B' },
                                            { lbl: 'HIGH', val: 'HIGH', col: '#F97316' },
                                            { lbl: 'CRITICAL', val: 'CRITICAL', col: '#EF4444' }
                                        ].map(s => (
                                            <button
                                                key={s.val}
                                                className={`fo-severity-btn ${formSeverity === s.val ? 'active' : ''}`}
                                                style={{ '--c': s.col, '--bg': formSeverity === s.val ? s.col : 'transparent' }}
                                                onClick={() => setFormSeverity(s.val)}
                                            >
                                                {s.lbl}
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                {/* Row 4 */}
                                <div className="fo-form-group">
                                    <label className="fo-muted-caps">Attach Photo Evidence</label>
                                    <div className="fo-upload-area">
                                        {!formFile ? (
                                            <>
                                                <Camera size={24} color="#555" style={{ marginBottom: 8 }} />
                                                <div style={{ fontSize: 13, color: '#888' }}>Click to upload or drag &amp; drop</div>
                                                <div style={{ fontSize: 11, color: '#555', marginTop: 4 }}>JPG, PNG up to 10MB</div>
                                                <input type="file" style={{ position: 'absolute', inset: 0, opacity: 0, cursor: 'pointer' }} onChange={handleFileChange} />
                                            </>
                                        ) : (
                                            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
                                                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                                    <div style={{ background: '#16A34A22', color: '#22C55E', padding: 6, borderRadius: 4 }}><Check size={16} /></div>
                                                    <div style={{ textAlign: 'left' }}>
                                                        <div style={{ fontSize: 13, color: '#FFF' }}>{formFile.name}</div>
                                                        <div style={{ fontSize: 11, color: '#666' }}>{(formFile.size / 1024 / 1024).toFixed(2)} MB</div>
                                                    </div>
                                                </div>
                                                <button style={{ background: 'transparent', border: 'none', color: '#666', cursor: 'pointer' }} onClick={() => setFormFile(null)}>
                                                    <X size={16} />
                                                </button>
                                            </div>
                                        )}
                                    </div>
                                </div>
                                <div className="fo-form-group">
                                    <label className="fo-muted-caps">Estimated Scale</label>
                                    <select className="fo-input" value={formScale} onChange={e => setFormScale(e.target.value)} style={{ marginBottom: 16 }}>
                                        <option value="Small (< 1 sq km)">Small (&lt; 1 sq km)</option>
                                        <option value="Medium (1-10 sq km)">Medium (1-10 sq km)</option>
                                        <option value="Large (10-100 sq km)">Large (10-100 sq km)</option>
                                        <option value="Massive (> 100 sq km)">Massive (&gt; 100 sq km)</option>
                                    </select>
                                    <label className="fo-muted-caps">Additional Notes</label>
                                    <textarea
                                        className="fo-input"
                                        style={{ height: 80, resize: 'vertical' }}
                                        value={formNotes} onChange={e => setFormNotes(e.target.value)}
                                    />
                                </div>
                            </div>

                            <button
                                className="fo-submit-btn"
                                disabled={submitting}
                                onClick={submitObservation}
                                style={{ marginTop: 24 }}
                            >
                                {submitting ? <div className="spinner black"></div> : 'SUBMIT OBSERVATION →'}
                            </button>
                        </div>

                        {/* Section 4 — Observation History */}
                        <div className="fo-card" id="history-section" style={{ marginBottom: 16 }}>
                            <div className="fo-card-header" style={{ marginBottom: 16 }}>
                                <h3 style={{ margin: 0, fontSize: 20, color: '#FFF' }}>My Observation History</h3>
                                <div style={{ fontSize: 13, color: '#666' }}>{history.length} submissions</div>
                            </div>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                                {history.map(h => (
                                    <div
                                        key={h.id}
                                        className={`fo-history-card ${expandedCard === h.id ? 'expanded' : ''}`}
                                        onClick={() => setExpandedCard(expandedCard === h.id ? null : h.id)}
                                    >
                                        <div className="fo-history-top">
                                            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                                                <span className="mono" style={{ color: '#F59E0B', fontSize: 11, fontWeight: 700 }}>{h.id}</span>
                                                <span style={{ fontSize: 11, fontWeight: 700, background: `${STATUS_COLORS[h.status]}1A`, color: STATUS_COLORS[h.status], padding: '2px 8px', borderRadius: 4, letterSpacing: '0.04em' }}>
                                                    {h.status.toUpperCase()}
                                                </span>
                                            </div>
                                            <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                                                <div>
                                                    <span style={{ fontWeight: 700, color: '#FFF', marginRight: 8, fontSize: 14 }}>{h.zone}</span>
                                                    <span style={{ fontSize: 12, color: '#888' }}>{h.type}</span>
                                                </div>
                                                <span className="mono" style={{ fontSize: 11, color: '#666' }}>{h.time}</span>
                                                <ChevronDown size={16} color="#666" className={`fo-history-chevron ${expandedCard === h.id ? 'rotated' : ''}`} />
                                            </div>
                                        </div>
                                        <div className="fo-history-content">
                                            <div className="fo-history-inner">
                                                <p style={{ margin: '12px 0 16px', fontSize: 13, color: '#AAA', lineHeight: 1.5 }}>
                                                    {h.desc}
                                                    {h.flagged && <span style={{ display: 'block', color: '#EF4444', marginTop: 8, fontWeight: 600, padding: '8px 12px', background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.2)', borderRadius: 4 }}><AlertTriangle size={14} style={{ verticalAlign: 'middle', marginRight: 6 }} /> FLAGGED FOR URGENT REVIEW</span>}
                                                </p>
                                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid #1E1E1E', paddingTop: 12 }}>
                                                    <div style={{ display: 'flex', gap: 8 }}>
                                                        <RiskPill risk={h.severity} color={h.riskColor} />
                                                        <span style={{ background: '#1A1A1A', color: '#999', fontSize: 11, padding: '2px 8px', borderRadius: 4, fontWeight: 600 }}>{h.scale}</span>
                                                    </div>
                                                    {h.reviewer && (
                                                        <span style={{ fontSize: 11, color: '#555' }}>Reviewed by: <span style={{ color: '#888' }}>{h.reviewer}</span></span>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                    </div>
                    {/* Padding bottom */}
                    <div style={{ height: 60 }}></div>
                </main>
            </div>

            {/* Modals */}
            {showReportModal && <FOReportModal onClose={() => setShowReportModal(false)} onShowToast={msg => { setToast(msg); setTimeout(() => setToast(null), 3000); }} />}

            {/* Toast */}
            {toast && <div className="success-toast" style={{ zIndex: 9999, borderColor: '#22C55E', color: '#22C55E', background: 'rgba(34,197,94,0.1)' }}>{toast}</div>}
        </div>
    );
};

export default FieldOfficerDashboard;
