import React, { useState, useMemo, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    LayoutDashboard, Bell, Navigation, BarChart3, FileText,
    Settings, LogOut, ChevronLeft, ChevronRight, ChevronDown,
    Plus, Search, Download, Eye, X, FileX, Loader,
    Lock, User
} from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';
import { fetchReports, downloadReport } from '../api/api';
import './AnalystDashboard.css';
import './ReportsPage.css';

// ─── Constants ────────────────────────────────────────────────────────────────
const ZONES = ['Quetta', 'Kech', 'Zhob', 'Pishin', 'Swat', 'Dir'];

const ZONE_ID_MAP = {
    Quetta: 'quetta',
    Kech:   'kech',
    Zhob:   'zhob',
    Pishin: 'pishin',
    Swat:   'swat',
    Dir:    'dir',
};

const RISK_COLORS = {
    Critical: { bg: 'rgba(239,68,68,0.12)',  color: '#EF4444', border: 'rgba(239,68,68,0.3)' },
    High:     { bg: 'rgba(249,115,22,0.12)', color: '#F97316', border: 'rgba(249,115,22,0.3)' },
    Medium:   { bg: 'rgba(245,158,11,0.12)', color: '#F59E0B', border: 'rgba(245,158,11,0.3)' },
    Low:      { bg: 'rgba(34,197,94,0.12)',  color: '#22C55E', border: 'rgba(34,197,94,0.3)' },
};

const STATUS_COLORS = {
    Generated:  { bg: 'rgba(34,197,94,0.12)',  color: '#22C55E', border: 'rgba(34,197,94,0.3)' },
    Processing: { bg: 'rgba(245,158,11,0.12)', color: '#F59E0B', border: 'rgba(245,158,11,0.3)' },
    Failed:     { bg: 'rgba(239,68,68,0.12)',  color: '#EF4444', border: 'rgba(239,68,68,0.3)' },
};

// ─── Map backend log to report format ─────────────────────────────────────────
const mapLogToReport = (log, index) => ({
    id:     `RPT-${String(index + 1).padStart(3, '0')}`,
    zone:   log.detail?.replace('PDF report for ', '') || 'Unknown',
    type:   'Full Report',
    risk:   'Medium',
    by:     log.user_id || 'System',
    date:   log.timestamp
        ? new Date(log.timestamp).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
        : 'N/A',
    status: 'Generated',
    log_id: log.log_id,
});

// ─── Pill helpers ─────────────────────────────────────────────────────────────
const RiskPill = ({ risk }) => {
    const c = RISK_COLORS[risk] || RISK_COLORS.Low;
    return (
        <span style={{ background: c.bg, color: c.color, border: `1px solid ${c.border}`, borderRadius: 4, padding: '2px 9px', fontSize: 11, fontWeight: 700, letterSpacing: '0.03em', display: 'inline-block' }}>
            {risk.toUpperCase()}
        </span>
    );
};

const StatusPill = ({ status }) => {
    const c = STATUS_COLORS[status] || STATUS_COLORS.Generated;
    return (
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, background: c.bg, color: c.color, border: `1px solid ${c.border}`, borderRadius: 4, padding: '2px 9px', fontSize: 11, fontWeight: 700 }}>
            {status === 'Processing' && <Loader size={10} style={{ animation: 'spin 1s linear infinite' }} />}
            {status}
        </span>
    );
};

// ─── View Report Modal ────────────────────────────────────────────────────────
const ViewReportModal = ({ report, onClose, onDownload }) => {
    if (!report) return null;
    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal-card" style={{ width: 520 }} onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h3>Report Details</h3>
                    <button className="close-btn" onClick={onClose}><X size={18} /></button>
                </div>
                <div className="topbar-divider" style={{ width: '100%', margin: '16px 0' }}></div>
                <div className="modal-body">
                    <div className="rpt-meta-grid">
                        {[
                            ['Report ID', <span className="mono" style={{ color: '#F59E0B' }}>{report.id}</span>],
                            ['Zone',      report.zone],
                            ['Type',      report.type],
                            ['Risk Level',<RiskPill risk={report.risk} />],
                            ['Generated By', report.by],
                            ['Date',      report.date],
                            ['Status',    <StatusPill status={report.status} />],
                        ].map(([k, v]) => (
                            <div key={k} className="rpt-meta-row">
                                <span className="rpt-meta-key">{k}</span>
                                <span className="rpt-meta-val">{v}</span>
                            </div>
                        ))}
                    </div>
                    <div className="topbar-divider" style={{ width: '100%', margin: '16px 0' }}></div>
                    <div style={{ fontSize: 11, color: '#555', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 10 }}>Report Summary</div>
                    <div className="rpt-summary-box">
                        Zone risk analysis report for {report.zone}. Generated on {report.date}.
                        Click download to get the full PDF report with detection events and risk scores.
                    </div>
                    <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
                        <button className="drawer-btn btn-outline" style={{ padding: '10px 20px', fontSize: 13, borderRadius: 6 }} onClick={onClose}>Close</button>
                        <button className="generate-btn" style={{ width: 'auto', padding: '10px 20px' }} onClick={() => onDownload(report)}>
                            <Download size={14} style={{ marginRight: 6 }} />Download PDF
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

// ─── Generate New Report Modal ────────────────────────────────────────────────
const GenerateModal = ({ onClose, onGenerated }) => {
    const [zone, setZone]             = useState(ZONES[0]);
    const [reportType, setReportType] = useState('Full Report');
    const [fromDate, setFromDate]     = useState('2026-02-21');
    const [toDate, setToDate]         = useState('2026-02-28');
    const [includeCharts, setIncludeCharts] = useState(true);
    const [generating, setGenerating] = useState(false);

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            const zoneId = ZONE_ID_MAP[zone] || zone.toLowerCase() || 'quetta';
            await downloadReport(zoneId);

            const newReport = {
                id:     `RPT-${String(Math.floor(Math.random() * 900) + 100)}`,
                zone,
                type:   reportType,
                risk:   'Medium',
                by:     'Current User',
                date:   new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
                status: 'Generated',
            };
            onClose();
            onGenerated(newReport, 'Report downloaded successfully');
        } catch (err) {
            console.error('Report generation failed:', err);
            setGenerating(false);
            onGenerated(null, 'Report generation failed — check connection');
        }
    };

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal-card" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h3>Generate New Report</h3>
                    <button className="close-btn" onClick={onClose}><X size={18} /></button>
                </div>
                <div className="topbar-divider" style={{ width: '100%', margin: '16px 0' }}></div>
                <div className="modal-body">
                    <div className="input-group">
                        <label>Zone</label>
                        <select className="modal-input" value={zone} onChange={e => setZone(e.target.value)} style={{ cursor: 'pointer' }}>
                            {ZONES.map(z => <option key={z}>{z}</option>)}
                        </select>
                    </div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <div className="input-group"><label>From</label><input type="date" value={fromDate} onChange={e => setFromDate(e.target.value)} className="modal-input" /></div>
                        <div className="input-group"><label>To</label><input type="date" value={toDate} onChange={e => setToDate(e.target.value)} className="modal-input" /></div>
                    </div>
                    <div className="input-group">
                        <label>Report Type</label>
                        <div className="pill-group">
                            {['Risk Analysis', 'Movement Summary', 'Full Report'].map(t => (
                                <button key={t} className={`pill-btn ${reportType === t ? 'active' : ''}`} onClick={() => setReportType(t)}>{t}</button>
                            ))}
                        </div>
                    </div>
                    <div className="toggle-group">
                        <span>Include Charts</span>
                        <label className="switch">
                            <input type="checkbox" checked={includeCharts} onChange={() => setIncludeCharts(!includeCharts)} />
                            <span className="slider round"></span>
                        </label>
                    </div>
                    <button className="generate-btn" disabled={generating} onClick={handleGenerate}>
                        {generating ? <div className="spinner"></div> : 'GENERATE PDF →'}
                    </button>
                </div>
            </div>
        </div>
    );
};

// ─── Main Reports Page ────────────────────────────────────────────────────────
const ReportsPage = () => {
    const navigate = useNavigate();
    const [sidebarCollapsed, setSidebarCollapsed] = useState(window.innerWidth <= 768);
    const [reports, setReports]       = useState([]);
    const [search, setSearch]         = useState('');
    const [filterZone, setFilterZone] = useState('All Zones');
    const [filterRisk, setFilterRisk] = useState('All Levels');
    const [filterType, setFilterType] = useState('All Types');
    const [filterFrom, setFilterFrom] = useState('');
    const [filterTo, setFilterTo]     = useState('');
    const [viewReport, setViewReport] = useState(null);
    const [showGenerate, setShowGenerate] = useState(false);
    const [toast, setToast]           = useState(null);

    // ── Fetch real reports from backend ───────────────
    useEffect(() => {
        const loadReports = async () => {
            try {
                const data = await fetchReports();
                if (data && data.length > 0) {
                    setReports(data.map(mapLogToReport));
                }
            } catch (err) {
                console.error('Failed to load reports:', err);
            }
        };
        loadReports();
    }, []);

    const showToast = (msg) => {
        setToast(msg);
        setTimeout(() => setToast(null), 3000);
    };

    const clearFilters = () => {
        setSearch(''); setFilterZone('All Zones'); setFilterRisk('All Levels');
        setFilterType('All Types'); setFilterFrom(''); setFilterTo('');
    };

    // ── Real PDF download ─────────────────────────────
    const handleDownload = async (report) => {
        try {
            const zoneId = ZONE_ID_MAP[report.zone] || report.zone?.toLowerCase() || 'quetta';
            await downloadReport(zoneId);
            showToast(`Report for ${report.zone} downloaded`);
        } catch (err) {
            console.error('Download failed:', err);
            showToast('Download failed — try again');
        }
    };

    const filtered = useMemo(() => reports.filter(r => {
        if (search && !r.id.toLowerCase().includes(search.toLowerCase()) && !r.zone.toLowerCase().includes(search.toLowerCase())) return false;
        if (filterZone !== 'All Zones' && r.zone !== filterZone) return false;
        if (filterRisk !== 'All Levels' && r.risk !== filterRisk) return false;
        if (filterType !== 'All Types' && r.type !== filterType) return false;
        return true;
    }), [reports, search, filterZone, filterRisk, filterType]);

    const stats = useMemo(() => ({
        total:      reports.length,
        thisWeek:   reports.filter(r => {
            const d = new Date(r.date);
            const now = new Date();
            return (now - d) < 7 * 24 * 60 * 60 * 1000;
        }).length,
        processing: reports.filter(r => r.status === 'Processing').length,
        failed:     reports.filter(r => r.status === 'Failed').length,
    }), [reports]);

    const handleGenerated = (newReport, msg) => {
        setReports(prev => [newReport, ...prev]);
        showToast(msg);
    };

    const selectStyle = {
        background: '#111111', border: '1px solid #2A2A2A', color: '#F5F5F5',
        borderRadius: 6, padding: '8px 12px', fontSize: 13, cursor: 'pointer',
        outline: 'none', fontFamily: 'inherit',
    };

    return (
        <div className="dashboard-container">
            <Topbar subtitle="Reports" onMenuClick={() => setSidebarCollapsed(!sidebarCollapsed)} />

            <div className="main-wrapper">
                <Sidebar collapsed={sidebarCollapsed} setCollapsed={setSidebarCollapsed} />

                <main style={{ flex: 1, overflowY: 'auto', padding: 28, display: 'flex', flexDirection: 'column', gap: 20 }}>

                    {/* ── Page Header ── */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                        <div>
                            <h1 style={{ margin: 0, fontSize: 26, fontWeight: 800, color: '#F5F5F5', letterSpacing: '-0.01em' }}>Reports</h1>
                            <p style={{ margin: '4px 0 0', fontSize: 13, color: '#555' }}>Manage and download generated zone analysis reports</p>
                        </div>
                        <button
                            className="generate-btn"
                            style={{ width: 'auto', padding: '10px 20px', display: 'inline-flex', alignItems: 'center', gap: 8 }}
                            onClick={() => setShowGenerate(true)}
                        >
                            <Plus size={15} />Generate New Report
                        </button>
                    </div>

                    {/* ── Filter Bar ── */}
                    <div style={{ background: '#0D0D0D', border: '1px solid #1E1E1E', borderRadius: 8, padding: '14px 20px', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
                        <div style={{ position: 'relative', width: 260 }}>
                            <Search size={14} style={{ position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: '#555' }} />
                            <input
                                type="text"
                                placeholder="Search by zone or report ID..."
                                value={search}
                                onChange={e => setSearch(e.target.value)}
                                style={{ ...selectStyle, paddingLeft: 32, width: '100%', boxSizing: 'border-box' }}
                            />
                        </div>
                        <select style={selectStyle} value={filterZone} onChange={e => setFilterZone(e.target.value)}>
                            <option>All Zones</option>
                            {ZONES.map(z => <option key={z}>{z}</option>)}
                        </select>
                        <select style={selectStyle} value={filterRisk} onChange={e => setFilterRisk(e.target.value)}>
                            {['All Levels', 'Critical', 'High', 'Medium', 'Low'].map(o => <option key={o}>{o}</option>)}
                        </select>
                        <select style={selectStyle} value={filterType} onChange={e => setFilterType(e.target.value)}>
                            {['All Types', 'Risk Analysis', 'Movement Summary', 'Full Report'].map(o => <option key={o}>{o}</option>)}
                        </select>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                            <label style={{ fontSize: 11, color: '#555', whiteSpace: 'nowrap' }}>From</label>
                            <input type="date" value={filterFrom} onChange={e => setFilterFrom(e.target.value)} style={{ ...selectStyle, padding: '7px 10px' }} />
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                            <label style={{ fontSize: 11, color: '#555' }}>To</label>
                            <input type="date" value={filterTo} onChange={e => setFilterTo(e.target.value)} style={{ ...selectStyle, padding: '7px 10px' }} />
                        </div>
                        <button
                            onClick={clearFilters}
                            style={{ background: 'transparent', border: '1px solid #F59E0B', color: '#F59E0B', borderRadius: 6, padding: '8px 14px', fontSize: 13, cursor: 'pointer', fontFamily: 'inherit', transition: 'background 0.15s', marginLeft: 'auto' }}
                            onMouseEnter={e => e.currentTarget.style.background = 'rgba(245,158,11,0.08)'}
                            onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                        >
                            Clear Filters
                        </button>
                    </div>

                    {/* ── Stat Cards ── */}
                    <div className="rpt-stats-grid">
                        {[
                            { label: 'Total Reports',           val: stats.total,      color: '#F5F5F5' },
                            { label: 'Generated This Week',     val: stats.thisWeek,   color: '#F59E0B' },
                            { label: 'Pending / Processing',    val: stats.processing, color: '#F97316' },
                            { label: 'Failed',                  val: stats.failed,     color: '#EF4444' },
                        ].map(s => (
                            <div key={s.label} style={{ background: '#0D0D0D', border: '1px solid #1E1E1E', borderRadius: 8, padding: '16px 20px' }}>
                                <div style={{ fontSize: 30, fontWeight: 800, color: s.color, lineHeight: 1, marginBottom: 6 }}>{s.val}</div>
                                <div style={{ fontSize: 11, color: '#555', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{s.label}</div>
                            </div>
                        ))}
                    </div>

                    {/* ── Reports Table ── */}
                    <div className="rpt-table-container">
                        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                            <thead>
                                <tr style={{ background: '#111111' }}>
                                    {['Report ID', 'Zone', 'Type', 'Risk Level', 'Generated By', 'Date', 'Status', 'Actions'].map(col => (
                                        <th key={col} style={{ padding: '12px 20px', textAlign: 'left', color: '#555555', fontFamily: 'Space Mono, monospace', fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase', fontWeight: 600, borderBottom: '1px solid #1A1A1A' }}>
                                            {col}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {filtered.length === 0 ? (
                                    <tr>
                                        <td colSpan={8}>
                                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '60px 20px', gap: 12 }}>
                                                <FileX size={40} color="#333" />
                                                <div style={{ fontSize: 16, fontWeight: 700, color: '#F5F5F5' }}>No reports found</div>
                                                <div style={{ fontSize: 13, color: '#555' }}>Generate your first report or adjust filters</div>
                                                <button onClick={clearFilters} style={{ background: 'transparent', border: 'none', color: '#F59E0B', cursor: 'pointer', fontSize: 13, padding: '4px 0' }}>Clear Filters</button>
                                            </div>
                                        </td>
                                    </tr>
                                ) : filtered.map((row, i) => (
                                    <tr
                                        key={row.id}
                                        style={{ background: i % 2 === 0 ? '#0D0D0D' : '#0F0F0F', transition: 'background 0.15s' }}
                                        onMouseEnter={e => e.currentTarget.style.background = '#141414'}
                                        onMouseLeave={e => e.currentTarget.style.background = i % 2 === 0 ? '#0D0D0D' : '#0F0F0F'}
                                    >
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A', fontFamily: 'Space Mono, monospace', fontSize: 12, color: '#F59E0B' }}>{row.id}</td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A', fontSize: 13 }}>{row.zone}</td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A', fontSize: 13, color: '#999' }}>{row.type}</td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A' }}><RiskPill risk={row.risk} /></td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A', fontSize: 13, color: '#999' }}>{row.by}</td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A', fontFamily: 'Space Mono, monospace', fontSize: 11, color: '#666' }}>{row.date}</td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A' }}><StatusPill status={row.status} /></td>
                                        <td style={{ padding: '14px 20px', borderBottom: '1px solid #1A1A1A' }}>
                                            <div style={{ display: 'flex', gap: 8 }}>
                                                <button
                                                    className="rpt-action-btn"
                                                    onClick={() => handleDownload(row)}
                                                    title="Download PDF"
                                                    style={{ background: '#161616', border: '1px solid #2A2A2A', color: '#F5F5F5' }}
                                                >
                                                    <Download size={13} />
                                                </button>
                                                <button
                                                    className="rpt-action-btn rpt-view-btn"
                                                    onClick={() => setViewReport(row)}
                                                    title="View"
                                                >
                                                    <Eye size={13} />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    {filtered.length > 0 && (
                        <div style={{ fontSize: 12, color: '#444', textAlign: 'right' }}>
                            Showing <span style={{ color: '#F59E0B' }}>{filtered.length}</span> of {reports.length} reports
                        </div>
                    )}
                </main>
            </div>

            {viewReport && (
                <ViewReportModal
                    report={viewReport}
                    onClose={() => setViewReport(null)}
                    onDownload={handleDownload}
                />
            )}
            {showGenerate && (
                <GenerateModal
                    onClose={() => setShowGenerate(false)}
                    onGenerated={handleGenerated}
                />
            )}

            {toast && <div className="success-toast">{toast}</div>}
            <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
        </div>
    );
};

export default ReportsPage;
